### ISSUE TITLE
Wrong boost version used for extraction in setup.sh?

### ISSUE THREAD

**Issue by shujaatak** [theilem/uavAP#1]
_#Get Boost 1.68.0
wget "https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz"
printf "\nExtracting boost 1.64.0\n"
tar -xzf boost_1_64_0.tar.gz
cd boost_1_64_0_

shouldn't it be?:

#Get Boost 1.68.0
wget "https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz"
printf "\nExtracting boost 1.6**8**.0\n"
tar -xzf boost_1_6**8**_0.tar.gz
cd boost_1_6**8**_0

**Comment by theilem** [comment]
Thank you, the issue has been fixed
