### ISSUE TITLE
Can uavAP be used with only X-Plane without Al Volo FC+DAQ system?

### ISSUE THREAD

**Issue by shujaatak** [theilem/uavAP#12]
I wonder if I can test uavAP using only X-Plane without Al Volo FC+DAQ system which I don't have at the moment.

Can you please mention a brief method how I can accomplish this?

**Comment by theilem** [comment]
You can use uavAP with X-Plane directly with the help of uavEE (https://github.com/theilem/uavEE.git). If you want to run uavAP directly on the same machine as X-Plane, you can select the sitl.json config in the XPlanePlugin of uavEE.

**Comment by shujaatak** [comment]
I am having problem building uavAP.

So far I have followed the following steps: 
I built and installed **cpsCore** by using the following commands (first I installed the required dependencies as mentioned in the cpsCore readme):
```
git clone --recurse-submodules https://github.com/theilem/cpsCore.git 

cd cpsCore
mkdir -p bld/release && cd bld/release

cmake -DCMAKE_BUILD_TYPE=Release ../../
make
make install
```
Then while being in the root directory of uavAP, I executed **setup.sh** from `uavAP/scripts/` which completed successfully without any errors.
Then I changed directory to `uavAP/bld/Release/` and tried to run `make` but I get this error:
```
 make
[  1%] Building CXX object Core/CMakeFiles/uavap_core.dir/DataHandling/DataHandling.o
/home/shujaat/Desktop/Qt_Workspace/Theilem-UAV/uavAP/src/Core/DataHandling/DataHandling.cpp:10:10: fatal error: uavAP/Core/DataHandling/DataHandling.h: No such file or directory
 #include <uavAP/Core/DataHandling/DataHandling.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Core/CMakeFiles/uavap_core.dir/build.make:62: recipe for target 'Core/CMakeFiles/uavap_core.dir/DataHandling/DataHandling.o' failed
make[2]: *** [Core/CMakeFiles/uavap_core.dir/DataHandling/DataHandling.o] Error 1
CMakeFiles/Makefile2:360: recipe for target 'Core/CMakeFiles/uavap_core.dir/all' failed
make[1]: *** [Core/CMakeFiles/uavap_core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```
Can you please tell what could be the possible cause of this error?

**Comment by shujaatak** [comment]
Probably **generate_proto.sh** is missing.

**Comment by theilem** [comment]
Try a clean new clone of uavAP master. Scripts are not needed anymore.

**Comment by shujaatak** [comment]
This worked!

```
git clone --recurse-submodules https://github.com/theilem/uavAP.git

cd uavAP
mkdir -p bld/release && cd bld/release

cmake -DCMAKE_BUILD_TYPE=Release ../../
make
make install
```
Readme file needs to be updated to reflect the new build method.

**Comment by shujaatak** [comment]
Can you please recommend the version of X-Plane that works with uavAP+uavEE?

On X-Plane website, I can see two kinds of versions:

- X-Plane 11 

- X-Plane 11 Professional-Use

**Comment by theilem** [comment]
Normal X-Plane11 is sufficient

**Comment by MacProSector** [comment]
> Can you please recommend the version of X-Plane that works with uavAP+uavEE?
> 
> On X-Plane website, I can see two kinds of versions:
> 
> * X-Plane 11
> * X-Plane 11 Professional-Use

X-Plane 11 on Steam also works fine.

**Comment by shujaatak** [comment]
I wonder if there is a way to connect to my Windows X-Plane 11(which I already have) from my Ubuntu system running uavAP?

Up till now I have successfully built and installed cpsCore, uavAP, uavEE, uavGS in Ubuntu but as I haven't used them before so its an another milestone for me to learn how to use them, I mean I have to learn which software I have to start first then another etc so that I get a properly working system.
