### ISSUE TITLE
How to setup/configure/test uavAP, uavEE, uavGS?

### ISSUE THREAD

**Issue by shujaatak** [theilem/uavAP#13]
Installed X-Plane-11 in the same ubuntu machine on which I built and installed cpsCore, uavAP, uavGS, and uavEE. 
I also installed X-Plane plugin according to the instructions given in the readme file of  uavEE.
I ran the x-plane plugin according to the instructions given in the readme file of  uavEE:

- Started a new flight in XPlane.
- Clicked Plugins/uavEE/Select Config/**sitl.json**
- Clicked Plugins/uavEE/**Start Node**
- Clicked Plugins/uavEE/**Enable Autopilot**

Then I ran uavGS with config file pulsar.json as command argument but console gives error then I tried pulsar_redis.json but it also gives error and then I tried pulsar_tnt.json which at least let me see the uavGS gui but without any activity happening.

As I have built and installed everything, now I want to know **what steps I should follow to run them in correct manner**?

**Comment by shujaatak** [comment]
I select Cessna for flight if that matters.

**Comment by shujaatak** [comment]
Hmm, as there isn't any concrete  **setup guide** so I am like a discoverer :) 

First I started X-Plane-11 in a terminal, selected **Cessna**, set location **Seattle Tacoma Intl**. I am running the X-Plane-11 on the same machine on which I have uavAP etc, I selected **sitl.json**, **started node**, and **enabled autopilot**.

![Screenshot from 2020-09-06 11-42-31](https://user-images.githubusercontent.com/14161646/92319867-3f5a3c80-f036-11ea-943c-dec99117ae9b.png)

Secondly, as I have **make** and **make install**ed cpsCore and uavAP so I ran the following command in a separate terminal to run **Watchdog** with **cessna_xplane.json**(I don't know if that's the right way and sequence):

`/usr/local/bin/uavAP/Watchdog /usr/local/config/cessna_xplane.json`

But I get this error continuously in the terminal in which I run Watchdog:

```
[Communication] [ERROR] [/home/shujaat/Desktop/Qt_Workspace/Theilem-UAV/cpsCore/src/Utilities/IDC/NetworkLayer/Serial/SerialHandler.cpp:166] Error while sending: Invalid argument
[Communication] [ERROR] [/home/shujaat/Desktop/Qt_Workspace/Theilem-UAV/cpsCore/src/Utilities/IDC/NetworkLayer/Serial/SerialHandler.cpp:166] Error while sending: Invalid argument
[Communication] [ERROR] [/home/shujaat/Desktop/Qt_Workspace/Theilem-UAV/cpsCore/src/Utilities/IDC/NetworkLayer/Serial/SerialHandler.cpp:166] Error while sending: Invalid argument
[Communication] [ERROR] [/home/shujaat/Desktop/Qt_Workspace/Theilem-UAV/cpsCore/src/Utilities/IDC/NetworkLayer/Serial/SerialHandler.cpp:166] Error while sending: Invalid argument
[Communication] [ERROR] [/home/shujaat/Desktop/Qt_Workspace/Theilem-UAV/cpsCore/src/Utilities/IDC/NetworkLayer/Serial/SerialHandler.cpp:166] Error while sending: Invalid argument
[Communication] [ERROR] [/home/shujaat/Desktop/Qt_Workspace/Theilem-UAV/cpsCore/src/Utilities/IDC/NetworkLayer/Serial/SerialHandler.cpp:166] Error while sending: Invalid argument

```
Thirdly, I run **uavGS** for monitoring, as I don't know which config file I should use so I tested all config files(pulsar.json, pulsar_redis, pulsar_tnt.json) but none of them working. Although in case of pulsar_tnt.json the uavGS gui appear successfully but without any data communication. Note I have installed **tty0tty** null modem emulator.

It would be helpful if you please help me figure out what am I doing wrong.

**Comment by shujaatak** [comment]
Most **probably** I face problems due to configuration issues?

**Comment by theilem** [comment]
You ran the correct configuration and order, but there was a bug in the delimiter string of the cessna_xplane/communication.json config. It is fixed now and it should work after reinstalling uavAP. To summarize:

1. Start XPlane, select config and start node -> this will create the shared memory object for sensor_data needed by uavAP
2. Start uavGS with pulsar_tnt
3. Start uavAP with /usr/local/bin/uavAP/Watchdog /usr/local/config/cessna_xplane.json
4. Release the brake in XPlane (press b) and enable autopilot. Maybe take off first since this might be rough.

Depending on where you want to fly in XPlane you should adjust the local frame in cessna_xplane/mission_control.json to somewhere near the runway. Let me know if it works.

**Comment by shujaatak** [comment]
**Thank you so much!** It worked! :)
