### ISSUE TITLE
How to implement/set custom mission and run it on autopilot?

### ISSUE THREAD

**Issue by shujaatak** [theilem/uavAP#14]
As expected I tried _**to discover**_ how to implement/set **custom mission** and run it on autopilot but I apparently failed as I could not figure out any option in uavGS and uavAP.

**Comment by shujaatak** [comment]
One thing I noticed that when I enable autopilot, by default aircraft starts descending and after some time it lands anywhere in a random location(not runway). I don't know if it's expected behavior.

**Comment by theilem** [comment]
The first critical thing is to set the local_frame correctly. Then you can create a new mission in the mission_control.json by following the examples of the implemented missions.

uavGS does not know the missions that are available on start-up. If you want to select and change missions you have to click on "update list" on the bottom left of the ground station. Then you can select them and click on send mission.

**Comment by theilem** [comment]
And pull again
